name: Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run prettier
        run: npm run prettier

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test

      - name: TypeScript Check
        run: npx tsc --noEmit

      - name: Build
        run: npm run build
